### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by 0xNino** [ngda-sil/Libft#1]
Bonsoir, j'ai remarqué que vous avez volé des bouts de code de ma libft, je vous demande donc de les supprimer tout de suite.

Meilleures salutations,

🤓

**Comment by ngda-sil** [comment]
Bonsoir,

Nous avons pris votre remarque avec beaucoup de sérieux. Après vérification faite par le bureau des plagiats, il a été constaté que le pourcentage de similitude est trop faible pour être considéré comme du plagiat et ne nécessite donc pas de retrait.

Meilleures salutations,

🤪

Le 8 avr. 2022 à 13:24, 0xNino ***@***.***> a écrit :

﻿

Bonsoir, j'ai remarqué que vous avez volé des bouts de code de ma libft, je vous demande donc de les supprimer tout de suite.

Meilleures salutations,

🤓

**Comment by 0xNino** [comment]
C'est noté, je ferme donc cette issue et vous souhaite une très bonne soirée.

P.S. très joli Makefile.
